### ISSUE TITLE
Pass props from each page to layout

### ISSUE THREAD

**Issue by jose-donato** [moxystudio/next-layout#5]
Hello.

With this library is it possible to pass props from different pages to the layout component?

For example, imagine:
- I have a contacts page, about page and a MainLayout.
- want to pass some props to MainLayout from the contacts page but different props from the about page.

Greetings and thanks for the library.

**Comment by satazor** [comment]
Hello @jose-donato.

Yes it's possible. Check https://github.com/moxystudio/next-layout#withlayoutmaplayoutstatetolayouttree-initiallayoutstatepage.

Basically you can do:

```js
// about page
export default withoutLayout(<MainLayout foo="bar" />)(AboutPage);
```

```js
// contacts page
export default withoutLayout(<MainLayout foo="baz" />)(ContactsPage);
```

Cheers.

**Comment by jose-donato** [comment]
Thanks for the answer.

There's any option to perform some information that comes from a network request for the layout? i mean, imagine i have to query a set of categories (from the backend) to display on the layout

**Comment by madeleineostoja** [comment]
Pretty sure this isn't possible if you want to use next's `getStaticProps`/etc data layer, because that's passed to the page component. I ran into the same issue, ended up not being able to use persistent layouts because my layouts required data fetched in a `getStaticProps` call.

**Comment by jose-donato** [comment]
hello! I ended up figuring out a solution and it is possible with next.js

let's say you are calling the layout component from _app.js, you can then
forward the props that come from getStaticProps to this layout component

**Comment by madeleineostoja** [comment]
Oh! Easy, is that with `next-layout`, or just a statically defined layout with Next alone? Don't suppose you have an example?

**Comment by jose-donato** [comment]
statically defined layout with next alone!

> Don't suppose you have an example?

Of course, the snippets needed:
in the static page you would do the api call:

```
export async function getStaticProps() {
    const [content] = await fetchApiCall()
    return {
        props: { content },
        revalidate: 1
    }
}
```

and in _app.js pass the desired props to the layout component:
```
import Layout from "@/components/Layout"

function MyApp({ Component, pageProps }) {
return <Layout
    content={pageProps.content}>
    <Component {...pageProps} />
</Layout>
}
```
